# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensores.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensores.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0esensores.proto\"7\n\x12Sensor_Temperatura\x12\x0c\n\x04nome\x18\x01 \x02(\t\x12\x13\n\x0btemperatura\x18\x02 \x01(\x02\"^\n\x1cSensor_Temperatura_Geladeira\x12\x0c\n\x04nome\x18\x01 \x02(\t\x12\x13\n\x0btemperatura\x18\x02 \x01(\x02\x12\x1b\n\x13temperatura_freezer\x18\x03 \x01(\x02\"2\n\x0fSensor_Presenca\x12\x0c\n\x04nome\x18\x01 \x02(\t\x12\x11\n\ttem_gente\x18\x02 \x01(\x08')
)




_SENSOR_TEMPERATURA = _descriptor.Descriptor(
  name='Sensor_Temperatura',
  full_name='Sensor_Temperatura',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='Sensor_Temperatura.nome', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperatura', full_name='Sensor_Temperatura.temperatura', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=73,
)


_SENSOR_TEMPERATURA_GELADEIRA = _descriptor.Descriptor(
  name='Sensor_Temperatura_Geladeira',
  full_name='Sensor_Temperatura_Geladeira',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='Sensor_Temperatura_Geladeira.nome', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperatura', full_name='Sensor_Temperatura_Geladeira.temperatura', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperatura_freezer', full_name='Sensor_Temperatura_Geladeira.temperatura_freezer', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=169,
)


_SENSOR_PRESENCA = _descriptor.Descriptor(
  name='Sensor_Presenca',
  full_name='Sensor_Presenca',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='Sensor_Presenca.nome', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tem_gente', full_name='Sensor_Presenca.tem_gente', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['Sensor_Temperatura'] = _SENSOR_TEMPERATURA
DESCRIPTOR.message_types_by_name['Sensor_Temperatura_Geladeira'] = _SENSOR_TEMPERATURA_GELADEIRA
DESCRIPTOR.message_types_by_name['Sensor_Presenca'] = _SENSOR_PRESENCA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sensor_Temperatura = _reflection.GeneratedProtocolMessageType('Sensor_Temperatura', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR_TEMPERATURA,
  __module__ = 'sensores_pb2'
  # @@protoc_insertion_point(class_scope:Sensor_Temperatura)
  ))
_sym_db.RegisterMessage(Sensor_Temperatura)

Sensor_Temperatura_Geladeira = _reflection.GeneratedProtocolMessageType('Sensor_Temperatura_Geladeira', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR_TEMPERATURA_GELADEIRA,
  __module__ = 'sensores_pb2'
  # @@protoc_insertion_point(class_scope:Sensor_Temperatura_Geladeira)
  ))
_sym_db.RegisterMessage(Sensor_Temperatura_Geladeira)

Sensor_Presenca = _reflection.GeneratedProtocolMessageType('Sensor_Presenca', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR_PRESENCA,
  __module__ = 'sensores_pb2'
  # @@protoc_insertion_point(class_scope:Sensor_Presenca)
  ))
_sym_db.RegisterMessage(Sensor_Presenca)


# @@protoc_insertion_point(module_scope)
