gnome-terminal -e "python3 client.py"
gnome-terminal -e "python3 -m gateway"
gnome-terminal -e "python3 -m devices.geladeira"
gnome-terminal -e "python3 -m devices.lampada"
gnome-terminal -e "python3 -m devices.tv"
gnome-terminal -e "python3 -m devices.ar-condicionado"
gnome-terminal -e "python3 -m sensores.termico"
gnome-terminal -e "python3 -m sensores.presenca"
gnome-terminal -e "python3 -m sensores.geladeira"
